from utils import *
def test_Similarity():
    
    seq1 = 'AAAAAAAAAACAGACAAAAAAAAAAAAACTTTAAACAAATAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA'
    seq2 = 'CGAAGCGCGAACAGGCGCCCGCCATAGAAGTGGGCCGTATCCCGGCTCCAACAACGGTCATGGTCCCGAACGATAACGCTGAACGTGGTCATCGGTGCAG'
    seq3 = 'CTGCACCGATGACCACGTTCAGCGTTATCGTTCGGGACCATGACCGTTGTTGGAGCCGGGATACGGCCCACTTCTATGGCGGGCGCCTGTTCGCGCTTCG'
    #print(gibbsFreeEnergy(seq1, seq2))
    #print(gibbsFreeEnergy(seq1, seq3))
    #print(gibbsFreeEnergy(seq2, seq3))
    print(binds_too_strongly(seq1, seq2))
    print(binds_too_strongly(seq1, seq3))
    print(binds_too_strongly(seq2, seq3))

def test_deltaGCalculation():
    from nupack import mfe
    dnaLibrary                 = ['CGAAGCGCGAACAGGCGCCCGCCATAGAAGTGGGCCGTATCCCGGCTCCAACAACGGTCATGGTCCCGAACGATAACGCTGAACGTGGTCATCGGTGCAG', 'CTGCACCGATGACCACGTTCAGCGTTATCGTTCGGGACCATGACCGTTGTTGGAGCCGGGATACGGCCCACTTCTATGGCGGGCGCCTGTTCGCGCTTCG']
    dnaLibraryANDnextCandidate = ['CGAAGCGCGAACAGGCGCCCGCCATAGAAGTGGGCCGTATCCCGGCTCCAACAACGGTCATGGTCCCGAACGATAACGCTGAACGTGGTCATCGGTGCAG', 'CTGCACCGATGACCACGTTCAGCGTTATCGTTCGGGACCATGACCGTTGTTGGAGCCGGGATACGGCCCACTTCTATGGCGGGCGCCTGTTCGCGCTTCG', 'AAAAAAAAAACAGACAAAAAAAAAAAAACTTTAAACAAATAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA']
    dnaLibraryAsComplex = Complex([Strand(string=s, name=f'strand_{s}') for s in dnaLibraryANDnextCandidateDNA])
    model = Model(material='dna', celsius=37, sodium=0.05)
    stabilityScore = mfe(dnaLibraryAsComplex, model=model)[0].energy
    print('OK')

test_Similarity()
